import type { DealAnalysis } from "./types";
import { buildAdvisorDealContext } from "./advisorContext";

export function generateThesisFitMemo(analysis: DealAnalysis): string {
  const ctx = buildAdvisorDealContext(analysis);
  return `# Buy Box Thesis Fit Report

**Deal:** ${analysis.companyName}  
**Thesis Fit Score:** ${ctx.thesisFitScore}/100  
**Bucket:** ${ctx.thesisBucket}  
**Exception Approved:** ${ctx.exceptionApproved ? "Yes" : "No"}

## Rationale
${ctx.thesisRationale}

## Red Flags Triggered
${ctx.thesisRedFlags.length > 0 ? ctx.thesisRedFlags.map((f) => `- ${f}`).join("\n") : "None"}

## Must-Have Criteria Blocked
${ctx.thesisMustHaveBlocked.length > 0 ? ctx.thesisMustHaveBlocked.map((b) => `- ${b}`).join("\n") : "None"}

---
*Generated by Acquisition OS Deterministic Engine*
`;
}

export function generateWorkingCapitalMemo(analysis: DealAnalysis): string {
  const ctx = buildAdvisorDealContext(analysis);
  return `# Working Capital Risk Assessment

**Deal:** ${analysis.companyName}  
**Status:** ${ctx.workingCapitalStatus}  
**Risk Level:** ${ctx.workingCapitalRisk}  
**Blocks Close Ready:** ${ctx.wcBlocksCloseReady ? "Yes" : "No"}

## Key Metrics
- Net Working Capital: $${(analysis.workingCapital.netWorkingCapital ?? 0).toLocaleString()}
- Estimated Peg: $${(analysis.workingCapital.estimatedPeg ?? 0).toLocaleString()}
- Cash Conversion Cycle: ${analysis.workingCapital.cashConversionDays ?? "missing"} days
- Liquidity Buffer Required: $${(analysis.workingCapital.liquidityBufferRequired ?? 0).toLocaleString()}

## Buyer Warnings
${ctx.workingCapitalWarnings.length > 0 ? ctx.workingCapitalWarnings.map((w) => `- ${w}`).join("\n") : "None"}

## Closing Adjustment
$${(analysis.workingCapital.closingAdjustment ?? 0).toLocaleString()}

---
*Generated by Acquisition OS Deterministic Engine*
`;
}

export function generateIntegrationMemo(analysis: DealAnalysis): string {
  const ctx = buildAdvisorDealContext(analysis);
  return `# Integration Readiness Assessment

**Deal:** ${analysis.companyName}  
**Readiness Score:** ${ctx.integrationReadinessScore.toFixed(0)}/100  
**Status:** ${ctx.integrationStatus}  
**100-Day Ready:** ${ctx.hundredDayReady ? "Yes" : "No"}  
**Can Close Safely:** ${ctx.canCloseSafely ? "Yes" : "No"}

## Integration Blockers
${ctx.integrationBlockers.length > 0 ? ctx.integrationBlockers.map((b) => `- ${b}`).join("\n") : "None"}

## Required Actions Before Close
${ctx.integrationRequiredActions.length > 0 ? ctx.integrationRequiredActions.map((a) => `- ${a}`).join("\n") : "None"}

## Risk Level
${ctx.integrationStatus === "ready" ? "Low" : ctx.integrationStatus === "in_progress" ? "Medium" : "High"}

---
*Generated by Acquisition OS Deterministic Engine*
`;
}

export function generateRedTeamMemo(analysis: DealAnalysis): string {
  const ctx = buildAdvisorDealContext(analysis);
  return `# Red Team Objection Report

**Deal:** ${analysis.companyName}  
**Unresolved Critical Objections:** ${ctx.unresolvedCriticalObjections}

## Top Objections
${ctx.redTeamTopObjections.length > 0 ? ctx.redTeamTopObjections.map((o) => `- ${o}`).join("\n") : "None"}

## Objection Details
${analysis.redTeam.objections
  .map(
    (obj) => `
### ${obj.prompt}
**Finding:** ${obj.finding}  
**Severity:** ${obj.severity}  
**Status:** ${obj.status}  
**Cleared:** ${obj.cleared ? "Yes" : "No"}  
**Evidence Needed:** ${obj.evidenceNeeded.join(", ")}  
**Owner:** ${obj.owner}
`,
  )
  .join("\n")}

---
*Generated by Acquisition OS Deterministic Engine*
`;
}

export function generateDealOnePager(analysis: DealAnalysis): string {
  const ctx = buildAdvisorDealContext(analysis);
  return `# ${analysis.companyName} — Deal One-Pager

**Verdict:** ${ctx.verdict} ${ctx.isPreliminary ? "(PRELIMINARY)" : ""}  
**Score:** ${ctx.scoreLabel} ${ctx.scoreOutOf100}/100  
**Confidence:** ${ctx.verdictConfidence}

## Headline Numbers
- **Revenue:** ${ctx.revenue}
- **Earnings (${ctx.earningsBasis}):** ${ctx.earnings}
- **Asking Price:** ${ctx.askingPrice}
- **EV/${ctx.earningsBasis}:** ${ctx.earningsBasis === "EBITDA" ? ctx.multipleEvEbitda : ctx.multipleEvSde}
- **DSCR (post-standby):** ${ctx.dscr.afterStandby}

## Capital Stack
${ctx.capitalStack.sba}  
${ctx.capitalStack.sellerNote}  
${ctx.capitalStack.buyerEquity}

## Thesis Fit
**Score:** ${ctx.thesisFitScore}/100 | **Bucket:** ${ctx.thesisBucket}

## Governance
**Passed:** ${ctx.governancePassedCount}/${ctx.governanceTotalCount} gates  
**IC Ready:** ${ctx.icReady ? "Yes" : "No"} | **LOI Ready:** ${ctx.loiReady ? "Yes" : "No"} | **Lender Ready:** ${ctx.lenderReady ? "Yes" : "No"}

## Freeze Status
**Status:** ${ctx.freezeStatus.toUpperCase()}  
${ctx.freezeTriggers.length > 0 ? `**Triggers:** ${ctx.freezeTriggers.join("; ")}` : ""}

## Next Action
${ctx.nextGovernanceAction}

---
*Generated by Acquisition OS Deterministic Engine*
`;
}

export function generateExpandedICMemo(analysis: DealAnalysis): string {
  const ctx = buildAdvisorDealContext(analysis);

  return `# Investment Committee Memorandum

## Executive Summary
**Company:** ${analysis.companyName}  
**Verdict:** ${ctx.verdict} ${ctx.isPreliminary ? "(PRELIMINARY)" : ""}  
**Score:** ${ctx.scoreLabel} ${ctx.scoreOutOf100}/100  
**Confidence:** ${ctx.verdictConfidence}  
**Recommendation:** ${ctx.nextActions[0] ?? "Continue diligence"}

---

## Deal Snapshot
| Metric | Value |
|--------|-------|
| Revenue | ${ctx.revenue} |
| Earnings (${ctx.earningsBasis}) | ${ctx.earnings} |
| Asking Price | ${ctx.askingPrice} |
| EV/${ctx.earningsBasis} | ${ctx.earningsBasis === "EBITDA" ? ctx.multipleEvEbitda : ctx.multipleEvSde} |
| EBITDA Margin | ${ctx.ebitdaMargin} |
| SDE Margin | ${ctx.sdeMargin} |

---

## Thesis Fit
**Score:** ${ctx.thesisFitScore}/100 | **Bucket:** ${ctx.thesisBucket}  
${ctx.thesisRationale}

${ctx.thesisRedFlags.length > 0 ? `**Red Flags:** ${ctx.thesisRedFlags.join(", ")}` : ""}

---

## Valuation
**Benchmark:** ${ctx.benchmark}  
**Band:** ${ctx.benchmarkBand}  
**Compatibility:** ${ctx.benchmarkCompatibility === "basis_match" ? "Direct comparison" : "Reference only"}  
**Band Position:** ${ctx.bandPosition}  
**Median Implied Value:** ${ctx.benchmarkMedianImpliedValue}  
**Value Gap vs Asking:** ${ctx.benchmarkValueGapVsAsking}

---

## Capital Stack
| Component | Amount |
|-----------|--------|
| SBA Loan | ${ctx.capitalStack.sba} |
| Seller Note | ${ctx.capitalStack.sellerNote} |
| Buyer Equity | ${ctx.capitalStack.buyerEquity} |
| **Total Sources** | **${ctx.capitalStack.totalSources}** |
| Difference vs PP | ${ctx.capitalStack.differenceVsPP} |

**Annual Debt Service:** ${ctx.capitalStack.totalAnnualDebtService}  
**Seller Note Standby:** ${ctx.capitalStack.sellerNoteStandby}

---

## DSCR Analysis
| Period | DSCR | Verdict |
|--------|------|---------|
| During Standby | ${ctx.dscr.duringStandby} | ${ctx.dscr.duringStandby} |
| After Standby | ${ctx.dscr.afterStandby} | ${ctx.dscr.verdict} |

---

## Risk Factors
${ctx.riskFactors.map((f) => `- **${f.label}:** ${f.level} (${f.score})\n  ${f.rationale}`).join("\n")}

**Risk Completeness:** ${ctx.riskCompletenessLabel}  
**Risk Confidence:** ${ctx.riskConfidence}

---

## Working Capital
**Status:** ${ctx.workingCapitalStatus}  
**Risk:** ${ctx.workingCapitalRisk}  
**Blocks Close Ready:** ${ctx.wcBlocksCloseReady ? "Yes" : "No"}

${ctx.workingCapitalWarnings.length > 0 ? `**Warnings:**\n${ctx.workingCapitalWarnings.map((w) => `- ${w}`).join("\n")}` : ""}

---

## Integration Readiness
**Score:** ${ctx.integrationReadinessScore.toFixed(0)}/100  
**Status:** ${ctx.integrationStatus}  
**100-Day Ready:** ${ctx.hundredDayReady ? "Yes" : "No"}  
**Can Close Safely:** ${ctx.canCloseSafely ? "Yes" : "No"}

${ctx.integrationBlockers.length > 0 ? `**Blockers:**\n${ctx.integrationBlockers.map((b) => `- ${b}`).join("\n")}` : ""}

---

## Governance Gates
**Passed:** ${ctx.governancePassedCount}/${ctx.governanceTotalCount}  
**IC Ready:** ${ctx.icReady ? "Yes" : "No"}  
**LOI Ready:** ${ctx.loiReady ? "Yes" : "No"}  
**Lender Ready:** ${ctx.lenderReady ? "Yes" : "No"}  
**Close Ready:** ${ctx.closeReady ? "Yes" : "No"}

${ctx.governanceBlockers.length > 0 ? `**Blockers:**\n${ctx.governanceBlockers.map((b) => `- ${b}`).join("\n")}` : ""}

---

## Freeze Status
**Status:** ${ctx.freezeStatus.toUpperCase()}  
${ctx.freezeTriggers.length > 0 ? `**Triggers:**\n${ctx.freezeTriggers.map((t) => `- ${t}`).join("\n")}` : ""}

---

## Red Team Objections
**Unresolved Critical:** ${ctx.unresolvedCriticalObjections}

${ctx.redTeamTopObjections.length > 0 ? `**Top Objections:**\n${ctx.redTeamTopObjections.map((o) => `- ${o}`).join("\n")}` : ""}

---

## Missing Data
**Critical:** ${ctx.missingCritical.length > 0 ? ctx.missingCritical.join(", ") : "None"}  
**Important:** ${ctx.missingImportant.length > 0 ? ctx.missingImportant.join(", ") : "None"}  
**Nice-to-Have:** ${ctx.missingNiceToHave.length > 0 ? ctx.missingNiceToHave.slice(0, 3).join(", ") : "None"}

---

## Confidence & Caveats
**Confidence Level:** ${ctx.verdictConfidence}  
**Reason:** ${ctx.verdictConfidenceReason}

**Benchmark Caveat:** ${ctx.benchmarkCompatibility === "basis_match" ? "Benchmark is a direct comparison." : "Benchmark is reference only — basis mismatch."}

**Do Not Rely On Until Verified:** ${ctx.missingCritical.length > 0 ? "Yes — critical data missing." : "No — core data complete."}

---

## Next Actions
${ctx.nextActions.map((a) => `- ${a}`).join("\n")}

---

*Generated by Acquisition OS Deterministic Engine*  
*Assumptions Used:* SBA ${(analysis.assumptions.sbaLoanPct * 100).toFixed(0)}% @ ${(analysis.assumptions.sbaInterestRate * 100).toFixed(1)}% for ${analysis.assumptions.sbaTermYears} years | Seller Note ${(analysis.assumptions.sellerNotePct * 100).toFixed(0)}% @ ${(analysis.assumptions.sellerNoteRate * 100).toFixed(1)}% for ${analysis.assumptions.sellerNoteTermYears} years (${analysis.assumptions.sellerNoteStandbyMonths}mo standby)
`;
}
