// Demo + test deal corpus.
//
//   isTest === true → REQUIRED_TEST_CASES (immutable, used by both unit tests
//                      and the UI's "Run Test Suite" button).
//   isDemo === true → DEMO_DEALS (live-feel pipeline so the empty state of a
//                      new install isn't blank, but still excluded from the
//                      strategic recommendations surface by default).

import type { DealInput } from "./types";

export const REQUIRED_TEST_CASES: DealInput[] = [
  {
    id: "test-1",
    companyName: "Strong Deal Test",
    industry: "plumbing",
    annualRevenue: 4_200_000,
    annualEBITDA: 1_100_000,
    askingPrice: 3_800_000,
    revenueTrend: "growing",
    ownerRole: "general manager",
    customerConcentrationPct: 12,
    employeeCount: 28,
    yearsInBusiness: 18,
    stage: "Under Analysis",
    isTest: true,
    diligence: {
      taxReturnsReceived: true,
      pnlReceived: true,
      balanceSheetReceived: true,
      addBacksDocumented: true,
      debtScheduleReceived: true,
    },
  },
  {
    id: "test-2",
    companyName: "Fair Deal Test",
    industry: "auto repair",
    annualRevenue: 2_400_000,
    annualEBITDA: 480_000,
    askingPrice: 1_550_000,
    revenueTrend: "flat",
    ownerRole: "owner-operator",
    customerConcentrationPct: 18,
    employeeCount: 14,
    yearsInBusiness: 22,
    stage: "Financials Requested",
    isTest: true,
    diligence: { pnlReceived: true, taxReturnsReceived: true },
  },
  {
    id: "test-3",
    companyName: "Overpriced Test",
    industry: "restaurant",
    annualRevenue: 1_800_000,
    annualEBITDA: 300_000,
    askingPrice: 1_800_000,
    revenueTrend: "flat",
    ownerRole: "owner-operator",
    customerConcentrationPct: 5,
    employeeCount: 22,
    yearsInBusiness: 11,
    stage: "Conversation Held",
    isTest: true,
    diligence: { pnlReceived: true },
  },
  {
    id: "test-4",
    companyName: "Revenue Trap Test",
    industry: "landscaping",
    annualRevenue: 3_000_000,
    annualEBITDA: 180_000,
    askingPrice: 900_000,
    revenueTrend: "growing",
    ownerRole: "owner-operator",
    customerConcentrationPct: 35,
    employeeCount: 25,
    yearsInBusiness: 9,
    stage: "Contacted",
    isTest: true,
    diligence: {},
  },
  {
    id: "test-5",
    companyName: "Small Undervalued Test",
    industry: "plumbing",
    annualRevenue: 900_000,
    annualEBITDA: 250_000,
    askingPrice: 650_000,
    revenueTrend: "growing",
    ownerRole: "owner-operator",
    customerConcentrationPct: 14,
    employeeCount: 6,
    yearsInBusiness: 14,
    stage: "Under Analysis",
    isTest: true,
    diligence: { pnlReceived: true, taxReturnsReceived: true, addBacksDocumented: true },
  },
  {
    id: "test-6",
    companyName: "Zero EBITDA Test",
    industry: "restaurant",
    annualRevenue: 1_000_000,
    annualEBITDA: 0,
    askingPrice: 1_200_000,
    revenueTrend: "declining",
    ownerRole: "owner-operator",
    customerConcentrationPct: 8,
    employeeCount: 12,
    yearsInBusiness: 6,
    stage: "Target Identified",
    isTest: true,
    diligence: {},
  },
  {
    id: "test-7",
    companyName: "Big Revenue Bad Earnings Test",
    industry: "it services",
    annualRevenue: 10_000_000,
    annualEBITDA: 400_000,
    askingPrice: 3_000_000,
    revenueTrend: "flat",
    ownerRole: "general manager",
    customerConcentrationPct: 45,
    employeeCount: 70,
    yearsInBusiness: 14,
    stage: "Conversation Held",
    isTest: true,
    diligence: { pnlReceived: true },
  },
  {
    id: "test-8",
    companyName: "Missing Asking Price Test",
    industry: "plumbing",
    annualRevenue: 2_000_000,
    annualEBITDA: 500_000,
    askingPrice: null,
    revenueTrend: "growing",
    ownerRole: "owner-operator",
    customerConcentrationPct: 10,
    employeeCount: 14,
    yearsInBusiness: 12,
    stage: "Conversation Held",
    isTest: true,
    diligence: { pnlReceived: true },
  },
];

export const DEMO_DEALS: DealInput[] = [
  {
    id: "demo-bluefield-hvac",
    companyName: "Bluefield HVAC",
    industry: "plumbing",
    location: "Asheville, NC",
    annualRevenue: 3_400_000,
    annualEBITDA: 820_000,
    askingPrice: 2_950_000,
    revenueTrend: "growing",
    ownerRole: "general manager",
    customerConcentrationPct: 9,
    recurringRevenuePct: 35,
    employeeCount: 24,
    yearsInBusiness: 21,
    stage: "Under Analysis",
    isDemo: true,
    diligence: {
      taxReturnsReceived: true,
      pnlReceived: true,
      balanceSheetReceived: true,
      addBacksDocumented: true,
      debtScheduleReceived: true,
      customerListReceived: true,
    },
  },
  {
    id: "demo-cypress-it",
    companyName: "Cypress IT Partners",
    industry: "it services",
    location: "Austin, TX",
    annualRevenue: 6_200_000,
    annualEBITDA: 1_350_000,
    askingPrice: 7_200_000,
    revenueTrend: "growing",
    ownerRole: "general manager",
    customerConcentrationPct: 22,
    recurringRevenuePct: 78,
    employeeCount: 42,
    yearsInBusiness: 13,
    stage: "LOI Submitted",
    isDemo: true,
    diligence: {
      taxReturnsReceived: true,
      pnlReceived: true,
      balanceSheetReceived: true,
      addBacksDocumented: true,
      debtScheduleReceived: true,
      customerListReceived: true,
      contractsReceived: true,
    },
  },
  {
    id: "demo-harborline-marine",
    companyName: "Harborline Marine Services",
    industry: "auto repair",
    location: "Tampa, FL",
    annualRevenue: 1_900_000,
    annualEBITDA: 220_000,
    askingPrice: 2_400_000,
    revenueTrend: "flat",
    ownerRole: "owner-operator",
    customerConcentrationPct: 40,
    employeeCount: 11,
    yearsInBusiness: 17,
    stage: "Conversation Held",
    isDemo: true,
    diligence: { pnlReceived: true },
  },
  {
    id: "demo-summit-roofing",
    companyName: "Summit Roofing Co.",
    industry: "roofing",
    location: "Denver, CO",
    annualRevenue: 4_800_000,
    annualEBITDA: 720_000,
    askingPrice: 2_650_000,
    revenueTrend: "growing",
    ownerRole: "owner-operator",
    customerConcentrationPct: 16,
    employeeCount: 32,
    yearsInBusiness: 10,
    stage: "Financials Requested",
    isDemo: true,
    diligence: { pnlReceived: true, taxReturnsReceived: true, addBacksDocumented: true },
  },
  {
    id: "demo-eastside-restaurant",
    companyName: "Eastside Café Group",
    industry: "restaurant",
    location: "Brooklyn, NY",
    annualRevenue: 2_100_000,
    annualEBITDA: -45_000,
    askingPrice: 1_300_000,
    revenueTrend: "declining",
    ownerRole: "owner-operator",
    customerConcentrationPct: 3,
    employeeCount: 28,
    yearsInBusiness: 7,
    stage: "Target Identified",
    isDemo: true,
    diligence: {},
  },
];
